domain: http://localhost:8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
aws:
  secretsmanager:
    name: clelab
  cloud:
    aws:
      region:
        static: ap-northeast-2
  ses:
    access-key: acesss-key
    secret-key: secret-key
    custom-secret: secret
    greeting-url: https://clelab-resource.s3.ap-northeast-2.amazonaws.com/templates/greeting.html
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
