domain: https://api.dev.clelab.io/
spring:
  jpa:
    properties:
      hibernate:
        ddl_auto: none
    open-in-view: false
aws:
  ses:
    greeting-url: https://elasticbeanstalk-ap-northeast-2-752764006166.s3.ap-northeast-2.amazonaws.com/resources/templates/greeting.html