spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
typeform:
  secret: local
aws:
  ses:
    access-key: acesss-key
    secret-key: secret-key
