domain: https://api.clelab.io
spring:
  jpa:
    properties:
      hibernate:
        ddl_auto: none
    open-in-view: false
aws:
  ses:
    greeting-url: https://clelab-resource.s3.ap-northeast-2.amazonaws.com/templates/greeting.html