name: PR Slack Notification
on:
  pull_request:
    branches:
      - main
  pull_request_review:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    name: Slack Notification
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Fire Notification
        uses: Lubycon/github-reviewer-slack-noti-action@v1.2.0
        with:
          slack-bot-token: ${{ secrets.LUBYCON_SLACK_BOT_TOKEN }}
          github-token: ${{ secrets.LUBYCON_GITHUB_TOKEN }}
          channel-id: 'C01V513LT6W'